<template>
  <div class="page">
    <h2>定义了一些通用css颜色样式，可直接复制后放在class里使用</h2>
    <span
      id="color0"
      class="span"
      style="background:#000000"
      data-clipboard-target="#color0"
    >black</span>
    <span
      id="color1"
      class="span"
      style="background:#0000FF"
      data-clipboard-target="#color1"
    >blue</span>
    <span
      id="color2"
      class="span"
      style="background:#8A2BE2"
      data-clipboard-target="#color2"
    >blueviolet</span>
    <span
      id="color3"
      class="span"
      style="background:#A52A2A"
      data-clipboard-target="#color3"
    >brown</span>
    <span
      id="color4"
      class="span"
      style="background:#DEB887"
      data-clipboard-target="#color4"
    >burlywood</span>
    <span
      id="color5"
      class="span"
      style="background:#5F9EA0"
      data-clipboard-target="#color5"
    >cadetblue</span>
    <span
      id="color7"
      class="span"
      style="background:#D2691E"
      data-clipboard-target="#color7"
    >chocolate</span>
    <span
      id="color8"
      class="span"
      style="background:#FF7F50"
      data-clipboard-target="#color8"
    >coral</span>
    <span
      id="color9"
      class="span"
      style="background:#6495ED"
      data-clipboard-target="#color9"
    >cornflowerblue</span>
    <span
      id="color10"
      class="span"
      style="background:#DC143C"
      data-clipboard-target="#color10"
    >crimson</span>
    <span
      id="color11"
      class="span"
      style="background:#00FFFF"
      data-clipboard-target="#color11"
    >cyan</span>
    <span
      id="color12"
      class="span"
      style="background:#00008B"
      data-clipboard-target="#color12"
    >darkblue</span>
    <span
      id="color13"
      class="span"
      style="background:#008B8B"
      data-clipboard-target="#color13"
    >darkcyan</span>
    <span
      id="color14"
      class="span"
      style="background:#B8860B"
      data-clipboard-target="#color14"
    >darkgoldenrod</span>
    <span
      id="color15"
      class="span"
      style="background:#A9A9A9"
      data-clipboard-target="#color15"
    >darkgray</span>
    <span
      id="color16"
      class="span"
      style="background:#006400"
      data-clipboard-target="#color16"
    >darkgreen</span>
    <span
      id="color17"
      class="span"
      style="background:#BDB76B"
      data-clipboard-target="#color17"
    >darkkhaki</span>
    <span
      id="color18"
      class="span"
      style="background:#8B008B"
      data-clipboard-target="#color18"
    >darkmagenta</span>
    <span
      id="color19"
      class="span"
      style="background:#556B2F"
      data-clipboard-target="#color19"
    >darkolivegreen</span>
    <span
      id="color20"
      class="span"
      style="background:#FF8C00"
      data-clipboard-target="#color20"
    >darkorange</span>
    <span
      id="color23"
      class="span"
      style="background:#E9967A"
      data-clipboard-target="#color23"
    >darksalmon</span>
    <span
      id="color24"
      class="span"
      style="background:#8FBC8F"
      data-clipboard-target="#color24"
    >darkseagreen</span>
    <span
      id="color26"
      class="span"
      style="background:#2F4F4F"
      data-clipboard-target="#color26"
    >darkslategray</span>
    <span
      id="color27"
      class="span"
      style="background:#00CED1"
      data-clipboard-target="#color27"
    >darkturquoise</span>
    <span
      id="color29"
      class="span"
      style="background:#FF1493"
      data-clipboard-target="#color29"
    >deeppink</span>
    <span
      id="color30"
      class="span"
      style="background:#00BFFF"
      data-clipboard-target="#color30"
    >deepskyblue</span>
    <span
      id="color31"
      class="span"
      style="background:#696969"
      data-clipboard-target="#color31"
    >dimgray</span>
    <span
      id="color32"
      class="span"
      style="background:#1E90FF"
      data-clipboard-target="#color32"
    >dodgerblue</span>
    <span
      id="color33"
      class="span"
      style="background:#D19275"
      data-clipboard-target="#color33"
    >feldspar</span>
    <span
      id="color34"
      class="span"
      style="background:#B22222"
      data-clipboard-target="#color34"
    >firebrick</span>
    <span
      id="color35"
      class="span"
      style="background:#228B22"
      data-clipboard-target="#color35"
    >forestgreen</span>
    <span
      id="color36"
      class="span"
      style="background:#FF00FF"
      data-clipboard-target="#color36"
    >fuchsia</span>
    <span
      id="color37"
      class="span"
      style="background:#FFD700"
      data-clipboard-target="#color37"
    >gold</span>
    <span
      id="color38"
      class="span"
      style="background:#DAA520"
      data-clipboard-target="#color38"
    >goldenrod</span>
    <span
      id="color39"
      class="span"
      style="background:#808080"
      data-clipboard-target="#color39"
    >gray</span>
    <span
      id="color40"
      class="span"
      style="background:#008000"
      data-clipboard-target="#color40"
    >green</span>
    <span
      id="color41"
      class="span"
      style="background:#FF69B4"
      data-clipboard-target="#color41"
    >hotpink</span>
    <span
      id="color42"
      class="span"
      style="background:#CD5C5C"
      data-clipboard-target="#color42"
    >indianred </span>
    <span
      id="color43"
      class="span"
      style="background:#4B0082"
      data-clipboard-target="#color43"
    >indigo </span>
    <span
      id="color44"
      class="span"
      style="background:#ADD8E6"
      data-clipboard-target="#color44"
    >lightblue</span>
    <span
      id="color45"
      class="span"
      style="background:#F08080"
      data-clipboard-target="#color45"
    >lightcoral</span>
    <span
      id="color46"
      class="span"
      style="background:#D3D3D3"
      data-clipboard-target="#color46"
    >lightgrey</span>
    <span
      id="color47"
      class="span"
      style="background:#90EE90"
      data-clipboard-target="#color47"
    >lightgreen</span>
    <span
      id="color48"
      class="span"
      style="background:#FFA07A"
      data-clipboard-target="#color48"
    >lightsalmon</span>
    <span
      id="color49"
      class="span"
      style="background:#20B2AA"
      data-clipboard-target="#color49"
    >lightseagreen</span>
    <span
      id="color50"
      class="span"
      style="background:#87CEFA"
      data-clipboard-target="#color50"
    >lightskyblue</span>
    <span
      id="color51"
      class="span"
      style="background:#8470FF"
      data-clipboard-target="#color51"
    >lightslateblue</span>
    <span
      id="color52"
      class="span"
      style="background:#B0C4DE"
      data-clipboard-target="#color52"
    >lightsteelblue</span>
    <span
      id="color53"
      class="span"
      style="background:#00FF00"
      data-clipboard-target="#color53"
    >lime</span>
    <span
      id="color54"
      class="span"
      style="background:#32CD32"
      data-clipboard-target="#color54"
    >limegreen</span>
    <span
      id="color56"
      class="span"
      style="background:#66CDAA"
      data-clipboard-target="#color56"
    >mediumaquamarine</span>
    <span
      id="color57"
      class="span"
      style="background:#0000CD"
      data-clipboard-target="#color57"
    >mediumblue</span>
    <span
      id="color58"
      class="span"
      style="background:#BA55D3"
      data-clipboard-target="#color58"
    >mediumorchid</span>
    <span
      id="color59"
      class="span"
      style="background:#9370D8"
      data-clipboard-target="#color59"
    >mediumpurple</span>
    <span
      id="color60"
      class="span"
      style="background:#3CB371"
      data-clipboard-target="#color60"
    >mediumseagreen</span>
    <span
      id="color61"
      class="span"
      style="background:#7B68EE"
      data-clipboard-target="#color61"
    >mediumslateblue</span>
    <span
      id="color62"
      class="span"
      style="background:#00FA9A"
      data-clipboard-target="#color62"
    >mediumspringgreen</span>
    <span
      id="color63"
      class="span"
      style="background:#48D1CC"
      data-clipboard-target="#color63"
    >mediumturquoise</span>
    <span
      id="color65"
      class="span"
      style="background:#191970"
      data-clipboard-target="#color65"
    >midnightblue</span>
    <span
      id="color66"
      class="span"
      style="background:#000080"
      data-clipboard-target="#color66"
    >navy</span>
    <span
      id="color67"
      class="span"
      style="background:#808000"
      data-clipboard-target="#color67"
    >olive</span>
    <span
      id="color68"
      class="span"
      style="background:#6B8E23"
      data-clipboard-target="#color68"
    >olivedrab</span>
    <span
      id="color69"
      class="span"
      style="background:#FFA500"
      data-clipboard-target="#color69"
    >orange</span>
    <span
      id="color70"
      class="span"
      style="background:#FF4500"
      data-clipboard-target="#color70"
    >orangered</span>
    <span
      id="color71"
      class="span"
      style="background:#DA70D6"
      data-clipboard-target="#color71"
    >orchid</span>
    <span
      id="color73"
      class="span"
      style="background:#D87093"
      data-clipboard-target="#color73"
    >palevioletred</span>
    <span
      id="color74"
      class="span"
      style="background:#CD853F"
      data-clipboard-target="#color74"
    >peru</span>
    <span
      id="color75"
      class="span"
      style="background:#DDA0DD"
      data-clipboard-target="#color75"
    >plum</span>
    <span
      id="color76"
      class="span"
      style="background:#B0E0E6"
      data-clipboard-target="#color76"
    >powderblue</span>
    <span
      id="color77"
      class="span"
      style="background:#800080"
      data-clipboard-target="#color77"
    >purple</span>
    <span
      id="color78"
      class="span"
      style="background:#FF0000"
      data-clipboard-target="#color78"
    >red</span>
    <span
      id="color79"
      class="span"
      style="background:#BC8F8F"
      data-clipboard-target="#color79"
    >rosybrown</span>
    <span
      id="color80"
      class="span"
      style="background:#4169E1"
      data-clipboard-target="#color80"
    >royalblue</span>
    <span
      id="color81"
      class="span"
      style="background:#FA8072"
      data-clipboard-target="#color81"
    >salmon</span>
    <span
      id="color82"
      class="span"
      style="background:#F4A460"
      data-clipboard-target="#color82"
    >sandybrown</span>
    <span
      id="color83"
      class="span"
      style="background:#2E8B57"
      data-clipboard-target="#color83"
    >seagreen</span>
    <span
      id="color84"
      class="span"
      style="background:#C0C0C0"
      data-clipboard-target="#color84"
    >silver</span>
    <span
      id="color85"
      class="span"
      style="background:#87CEEB"
      data-clipboard-target="#color85"
    >skyblue</span>
    <span
      id="color86"
      class="span"
      style="background:#6A5ACD"
      data-clipboard-target="#color86"
    >slateblue</span>
    <span
      id="color87"
      class="span"
      style="background:#708090"
      data-clipboard-target="#color87"
    >slategray</span>
    <span
      id="color89"
      class="span"
      style="background:#4682B4"
      data-clipboard-target="#color89"
    >steelblue</span>
    <span
      id="color90"
      class="span"
      style="background:#D2B48C"
      data-clipboard-target="#color90"
    >tan</span>
    <span
      id="color91"
      class="span"
      style="background:#008080"
      data-clipboard-target="#color91"
    >teal</span>
    <span
      id="color92"
      class="span"
      style="background:#D8BFD8"
      data-clipboard-target="#color92"
    >thistle</span>
    <span
      id="color93"
      class="span"
      style="background:#FF6347"
      data-clipboard-target="#color93"
    >tomato</span>
    <span
      id="color94"
      class="span"
      style="background:#EE82EE"
      data-clipboard-target="#color94"
    >violet</span>
    <span
      id="color95"
      class="span"
      style="background:#D02090"
      data-clipboard-target="#color95"
    >violetred</span>
    <span
      id="color96"
      class="span"
      style="background:#9ACD32"
      data-clipboard-target="#color96"
    >yellowgreen</span>
  </div>
</template>
<script lang="ts">
import { Component, Vue } from 'vue-property-decorator'
@Component({
})
export default class extends Vue {

}
</script>
<style lang="scss" scoped>
.page{
    padding: 20px;
}
 span {
     margin: 5px;
        display: inline-block;
        height: 35px;
        width: 120px;
        line-height: 35px;
        color: #fff;
        padding: 3px 10px;
        text-align: center;
        margin-bottom: 3px;
    }
    h2 {
        width:100%;
        text-align:center;
        margin-bottom:10px;
    }
</style>
